### ISSUE TITLE
Microsoft Edge Add-ins:  Read your browsing history

### ISSUE THREAD

**Issue by dajhorn** [meganz/web-extension#17]
As of today, the MEGA extension published at the [Microsoft Store](https://microsoftedge.microsoft.com/addons/detail/mega/jemjknhgpjaacbghpdhgchbgccbpkkgf) requires the "read your browsing history" and "block content on any page" permissions, so Microsoft Edge automatically disables it in existing installations.

![image](https://github.com/meganz/web-extension/assets/494022/231721c9-9c5b-4896-a8bc-aa30b219a80f)

This means the [Chrome Web Store](https://chromewebstore.google.com/detail/mega/bigefpfhnfcobdlfbedofhhaibnlghod) has a different build, but I don't see a corresponding commit in this repo or an explanation for why the builds are different.

Is an intentional change, and for what purpose?

**Comment by WednesdayManiac** [comment]
block content on any page? whaaat? why? and read my browsing history? why does it need that? Like if there was use sure. but I hit download and it actives that's it. How do these option add anything to that function?

**Comment by Blood-PawWerewolf** [comment]
this wouldn't be the first time, since MEGA's extention was once hijacked on chrome a few years ago.

**Comment by xWTF** [comment]
This permission appears to be introduced in the MV3 change: https://github.com/meganz/web-extension/commit/6be6449c413f41cbfa8585be20983b19079597a6
I wounder if there's another approach that declares site permissions explicitly instead of using the all site permission and filter from code.

**Comment by diegocr** [comment]
Thanks guys for coming to report this straight on the repo, where you can find the latest changes we've made.

as you may know, Google is deprecating the so called Manifest V2 extensions, you may read about it [here](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline)

Quoting:

> We will begin disabling Manifest V2 extensions in [pre-stable versions of Chrome](https://developer.chrome.com/docs/web-platform/chrome-release-channels) (Dev, Canary, and Beta) as early as June 2024, in Chrome 127 and later. Users impacted by the rollout will see Manifest V2 extensions automatically disabled in their browser and will no longer be able to install Manifest V2 extensions from the Chrome Web Store.

With that deprecation, comes new APIs we're forced to use, namely [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest)

It's by using this new API from where these new permissions arises, so you may see a bunch of other extension asking for them in the near future.

However, what is happening here seems to be a glitch on the browser side, since we're not meant to see the request for browsing history, as specified for Manifest V3 extension permissions, you may read about it [here](https://developer.chrome.com/docs/extensions/reference/permissions-list)

![242231093235](https://github.com/meganz/web-extension/assets/734313/34be10cf-faf9-4bd0-92e7-6a6aaf08478d)

So, while we're using that for development purposes, as stated there it must be ignored / unused for extensions installed form the app store(s).

Anyway, given that, we will proceed to disable `declarativeNetRequestFeedback` since we don't need it any longer.

Regarding the `Block content on any page` permission, that is raised by using `declarativeNetRequest` as you can find on the aforementioned page. Here we do only use this to redirect `https://mega.nz/**` URLs to be loaded through the extension, and only that.

https://github.com/meganz/web-extension/blob/6be6449c413f41cbfa8585be20983b19079597a6/mega.js#L25-L34

Hope this does bring some light on the matter, but happy to clarify anything else further if you guys consider it's needed.

**Comment by diegocr** [comment]
We've just published version 5.23.0, where only two permissions remains:

https://github.com/meganz/web-extension/blob/e92b3ee25a43217a2927f9c4fa2f8a976570adec/manifest.json#L11-L14

per commits 7017ed2facadddd4ef43ee38d99147c6f40137bc and e92b3ee25a43217a2927f9c4fa2f8a976570adec (ditched clipboard's copy/paste as well since we don't need it any longer)

**Comment by dajhorn** [comment]
This MEGA extension update is now visible to me in the official Edge Add-Ons catalog.

![image](https://github.com/meganz/web-extension/assets/494022/0dfa185d-7b62-4c30-828d-d9a534349232)

Permissions are now:
* Read and change your data on mega.nz
* Block content on any page

Thanks.
